CREATE TABLE IF NOT EXISTS blogs (
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    slug      TEXT NOT NULL UNIQUE,
    title     TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    thumbnail TEXT NOT NULL DEFAULT '',
    content   TEXT NOT NULL DEFAULT '',
    createdAt DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
